apiVersion: v1
kind: Pod
metadata:
  name: nginx-headless-pod
  labels:
    app: nginx-headless-pod
spec:
  hostname: nginx-headless-pod
  subdomain: nginx-headless-pod-service
  containers:
  - image: nginx
    name: nginx-headless-pod
    ports:
    - containerPort: 80
      name: web
      protocol: TCP
