apiVersion: v1
kind: Service
metadata:
  name: nginx-dns-service
spec:
  externalIPs:
  - 10.24.1.44 
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: nginx-dns
